# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: OLCUT CI (Ubuntu x86_64, OpenJDK 8, 11, 17)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against supported LTS versions and latest
        java: [ 8, 11, 17 ]
    name: OLCUT - Ubuntu OpenJDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  build-17:
    runs-on: ubuntu-latest
    name: OLCUT - Ubuntu Java SE 17
    steps:
      - uses: actions/checkout@v4
      - name: Setup Oracle Java SE
        uses: oracle-actions/setup-java@v1.4.0
        with:
          website: oracle.com
          release: 17
          version: 17.0.12
      - name: Build with Java 17
        run: mvn -B package --file pom.xml
