# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: OLCUT CI (Ubuntu x86_64, Java SE 17)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against supported LTS versions and latest
        java: [ 17 ]
    name: OLCUT - Ubuntu Java SE ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java Development Kits built by Oracle
        uses: oracle-actions/setup-java@v1.0.0
        with:
          release: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
